name: travis
description: A starting point for Dart libraries or applications.
version: 0.0.1-dev
author: Kevin Moore <kevmoo@google.com>
homepage: https://github.com/kevmoo/travis.dart
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:
  http: any
  path: any
  sdk_builds: '^0.0.1'
dev_dependencies:
  test: '^0.12.0'
